### ISSUE TITLE
The extention crashes when loading VSCode

### ISSUE THREAD

**Issue by feldim2425** [sanmont/vscode-kickass-studio#15]
I noticed that the only working feature seemed to be the language support. I could not find a way to debug or create launch tasks. The Extension Host printed an error during certain tasks like opening and saving a ``.asm`` file
Error log: https://pastebin.com/7i7wSPFe

System information:
OS / OS-Version: Ubuntu 20.04
VSCode Version: 1.47.2 (.deb Package not the snapcraft image)

**Comment by sanmont** [comment]
Hi @feldim2425, thanks for reaching and pointing out this. Im still fixing some bugs , also in the next major release (ETA 2 weeks) there will be basic support search for the definition, and references for labels.
I'll review the pr and if everything is ok merge it and publish a new version.
Thanks again for the interest, if you have any other suggestions of features let me know and Ill take them in consideration.
