### ISSUE TITLE
Adding segments causes debugging to stop working

### ISSUE THREAD

**Issue by RoyJacobs** [sanmont/vscode-kickass-studio#29]
Hi, I've set up a very basic project that works fine (https://github.com/RoyJacobs/c64-empty-vscode/). I can launch the application and it will build and then run via Vice.

However, once I start using KickAssembler Segments then the debugger hangs and it doesn't even launch Vice. Is this something I'm doing wrong on my end?

This is the change I've made to my project: https://github.com/RoyJacobs/c64-empty-vscode/pull/1/commits/be1df64c9e20ad1407e28bef812c822a17abf90e

You can check out the `segments` branch to reproduce.

**Comment by sanmont** [comment]
Hi Roy. I've never used kick assembler segments- Im going to investigate how these works an how it would affect the debugging.
Thanks!

**Comment by sanmont** [comment]
Hi @RoyJacobs ; Iǘe published a new version of kickassm studio with support for segments. It should be up now.

Delete the foldes .vscode and bin in your project to ake sure it takes the proper files.

Any other problem dont hesitate to contact me.
If you want you can follow me at 
https://twitter.com/sanmonterodev

**Comment by RoyJacobs** [comment]
It's working fine now, thanks for debugging :)
